# Generated by Django 4.2.3 on 2023-07-13 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Try',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Institute', models.CharField(max_length=400)),
                ('Academic_Program', models.CharField(max_length=400)),
                ('Quota', models.CharField(max_length=5)),
                ('Seat_type', models.CharField(max_length=20)),
                ('Gender', models.CharField(max_length=30)),
                ('Opening_Rank', models.CharField(max_length=10)),
                ('Closing_rank', models.CharField(max_length=10)),
                ('Year', models.IntegerField()),
                ('Round', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
