# Generated by Django 4.2.3 on 2023-07-13 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page1', '0002_try_delete_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='try',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
