# Generated by Django 4.2.3 on 2023-07-16 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page1', '0007_extract'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Try',
        ),
    ]
