# Generated by Django 4.2.3 on 2023-07-16 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page1', '0009_delete_data'),
    ]

    operations = [
        migrations.DeleteModel(
            name='info',
        ),
    ]
